In [2]:
import pandas as pd

import os
import s3fs
os.environ["AWS_ACCESS_KEY_ID"] = 'QC10FGDM44GPN2JG9UBO'
os.environ["AWS_SECRET_ACCESS_KEY"] = 'EnSNroO+mQ6eSfD+Hv6GulTpjlwRvsf+ZVPANhGD'
os.environ["AWS_SESSION_TOKEN"] = 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJRQzEwRkdETTQ0R1BOMkpHOVVCTyIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sImF1ZCI6WyJtaW5pby1kYXRhbm9kZSIsIm9ueXhpYSIsImFjY291bnQiXSwiYXV0aF90aW1lIjoxNzczMTQyMDYzLCJhenAiOiJvbnl4aWEiLCJjbmYiOnsiamt0IjoiejVuRThwN3BFNXRyaVFpREg5ZG1jVnFPMVZncTNPR3NzeG5ub29JNDR3dyJ9LCJlbWFpbCI6Imx1Y2FzLmN1bXVuZWxAZW5zYWUuZnIiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZXhwIjoxNzc0NjkyNjI1LCJmYW1pbHlfbmFtZSI6IkN1bXVuZWwiLCJnaXZlbl9uYW1lIjoiTHVjYXMiLCJncm91cHMiOlsiVVNFUl9PTllYSUEiLCJzdGF0YXBwLXNlZ21lZGljIl0sImlhdCI6MTc3NDA4NzgyNCwiaXNzIjoiaHR0cHM6Ly9hdXRoLmxhYi5zc3BjbG91ZC5mci9hdXRoL3JlYWxtcy9zc3BjbG91ZCIsImp0aSI6Im9ucnRydDo1NmQzMDg5OC1iYTkwLTRlY2EtNzlhOS1lN2ZjN2ZlZjcwNzgiLCJuYW1lIjoiTHVjYXMgQ3VtdW5lbCIsInBvbGljeSI6InN0c29ubHkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJsYWIiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtc3NwY2xvdWQiXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJyb2xlcyI6WyJvZmZsaW5lX2FjY2VzcyIsInVtYV9hdXRob3JpemF0aW9uIiwiZGVmYXVsdC1yb2xlcy1zc3BjbG91ZCJdLCJzY29wZSI6Im9wZW5pZCBwcm9maWxlIGdyb3VwcyBlbWFpbCIsInNpZCI6ImQwNDFjMGI3LTYxMzctOTVjMS1jM2IzLWQ2MGExMmEyNWM3ZiIsInN1YiI6ImUyZDc4NjRjLTcwMzItNDI0ZC04OTA2LWU0ZjhiNDFjYzAwMyIsInR5cCI6IkRQb1AifQ.8inWDRk1z0IJdSis7y7QQT9njBLDuCx9Ubx48bkO2n1L13MRsH71ah5yKpWU3npqI3E8eNHFwIIEyskNz0wi6A'
os.environ["AWS_DEFAULT_REGION"] = 'us-east-1'
fs = s3fs.S3FileSystem(
    client_kwargs={'endpoint_url': 'https://'+'minio.lab.sspcloud.fr'},
    key = os.environ["AWS_ACCESS_KEY_ID"], 
    secret = os.environ["AWS_SECRET_ACCESS_KEY"], 
    token = os.environ["AWS_SESSION_TOKEN"])

"""
with fs.open("s3://lab/art_net_dec.parquet") as f : 
    dfa = pd.read_parquet(f)

with fs.open("s3://lab/conf_net_dec.parquet") as f : 
    dfc = pd.read_parquet(f)"""

with fs.open("s3://lab/mem/full_name_list.csv") as f : 
    nl = pd.read_csv(f)

with fs.open("s3://lab/kgnd.csv") as f:
    kgnd = pd.read_csv(f)
with fs.open("s3://lab/ignd.csv") as f:
    ignd = pd.read_csv(f)
with fs.open("s3://lab/wgnd.csv") as f:
    wgnd = pd.read_csv(f)
with fs.open("s3://lab/jgnd.csv") as f:
    jgnd = pd.read_csv(f)
with fs.open("s3://lab/cgnd.csv") as f:
    cgnd = pd.read_csv(f)
with fs.open("s3://lab/usgnd.csv") as f: 
    usgnd = pd.read_csv(f)

In [ ]:
gnd=pd.concat([wgnd,cgnd,kgnd,ignd,jgnd,usgnd],axis=0,ignore_index=True)
gnd=gnd.drop(columns=["Count"])
gnd["Name"] = gnd["Name"].str.lower()
gnd = gnd.drop_duplicates()
gnd

                 Name Gender
0                baby      F
1              aisyah      F
2               anela      F
3               anela      F
4         fiyinfoluwa      F
...               ...    ...
27351475        Zylyn      M
27351476      Zymiere      M
27351477       Zypher      M
27351478         Zyre      M
27351479       Zyrell      M

[27351480 rows x 2 columns]

In [ ]:
#duplicates
pd.concat(g for _, g in gnd.groupby("Name") if len(g) > 1)

            Name Gender
15             a      M
17             a      F
1782       aabir      F
1783       aabir      M
3045         aad      F
...          ...    ...
26894631  zyonne      M
26753721   zyree      M
26776298   zyree      F
21168173   zyrie      F
27093256   zyrie      M

[74840 rows x 2 columns]

In [8]:
dfa["authors"] = dfa["authors"].apply(lambda lst: [d["name"] for d in lst])
dfc["authors"] = dfc["authors"].apply(lambda lst: [d["name"] for d in lst])

In [16]:
nla = dfa["authors"].explode().str.split(' ').str[0]
nlc = dfc["authors"].explode().str.split(' ').str[0]

In [19]:
nl = pd.concat([nla,nlc]).drop_duplicates()

In [49]:
nl = nl[~nl.str.contains(r"^[A-Za-z]\.$", na=False)]
nl = nl[~nl.str.contains(r"^[A-Za-z]\.-[A-Za-z]\.$", na=False)]
nl = nl[~nl.str.contains(r"^[A-Za-z]-[A-Za-z]\.$", na=False)]
nl = nl[~nl.str.contains(r"^[A-Za-z][A-Za-z]\.$", na=False)]
nl = nl[~nl.str.contains(r"^[A-Za-z][A-Za-z][A-Za-z]\.$", na=False)]

In [51]:
nl.to_csv("s3://lab/mem/full_name_list.csv")

In [52]:
nl

0                     Kai
1                 Richard
1                  Stefan
2                 Herbert
3                  Sophie
                ...
3749381          Siwaphon
3749388         Tasi-Ying
3749413           XiangXu
3749415    Pradhyumansinh
3749454              Chah
Name: authors, Length: 313632, dtype: object

In [53]:
!pip install gender-guesser

Collecting gender-guesser
  Downloading gender_guesser-0.4.0-py2.py3-none-any.whl.metadata (3.0 kB)
Downloading gender_guesser-0.4.0-py2.py3-none-any.whl (379 kB)
Installing collected packages: gender-guesser
Successfully installed gender-guesser-0.4.0

In [71]:
import gender_guesser.detector as gg

d = gg.Detector()
ng_dict = pd.DataFrame()
ng_dict["name"] = nl
ng_dict["gender"] = nl.apply(lambda x: d.get_gender(x))
ng_dict

                   name   gender
0                   Kai     male
1               Richard     male
1                Stefan     male
2               Herbert     male
3                Sophie   female
...                 ...      ...
3749381        Siwaphon  unknown
3749388       Tasi-Ying  unknown
3749413         XiangXu  unknown
3749415  Pradhyumansinh  unknown
3749454            Chah  unknown

[313632 rows x 2 columns]

In [72]:
ng_dict[ng_dict["gender"]=="unknown"]

                   name   gender
4                   NaN  unknown
27          Hans-Jürgen  unknown
42             Nicolaos  unknown
87         Brikenrikena  unknown
96              Catalin  unknown
...                 ...      ...
3749381        Siwaphon  unknown
3749388       Tasi-Ying  unknown
3749413         XiangXu  unknown
3749415  Pradhyumansinh  unknown
3749454            Chah  unknown

[280158 rows x 2 columns]